// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.DAL.Data;

#nullable disable

namespace MovieApp.DAL.Data.Migrations
{
    [DbContext(typeof(MovieAppDbContext))]
    [Migration("20260121124116_mig_4")]
    partial class mig_4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieApp.DAL.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Director", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "123 Hollywood Blvd, Los Angeles, CA",
                            Age = 77,
                            City = "Los Angeles",
                            Description = "An American filmmaker known for his work in the adventure and science fiction genres.",
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 2,
                            Adress = "456 Sunset St, Burbank, CA",
                            Age = 50,
                            City = "Burbank",
                            Description = "A British-American filmmaker known for his complex narratives and innovative storytelling techniques.",
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 3,
                            Adress = "789 Vine St, Los Angeles, CA",
                            Age = 58,
                            City = "Los Angeles",
                            Description = "An American filmmaker known for his stylized violence, sharp dialogue, and non-linear storytelling.",
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 4,
                            Adress = "321 Hollywood Blvd, New York, NY",
                            Age = 78,
                            City = "New York",
                            Description = "An American filmmaker known for his work in the crime and drama genres, often exploring themes of guilt and redemption.",
                            Name = "Martin Scorsese"
                        });
                });

            modelBuilder.Entity("MovieApp.DAL.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal>("Imdb")
                        .HasColumnType("decimal (18,2)");

                    b.Property<DateTime>("ReleaseYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A mind-bending thriller about dream invasion.",
                            DirectorId = 1,
                            Duration = 148,
                            Imdb = 8.8m,
                            ReleaseYear = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Batman faces the Joker in Gotham City.",
                            DirectorId = 1,
                            Duration = 152,
                            Imdb = 9.0m,
                            ReleaseYear = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Interwoven stories of crime in Los Angeles.",
                            DirectorId = 2,
                            Duration = 154,
                            Imdb = 8.9m,
                            ReleaseYear = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A bride seeks revenge on her former lover.",
                            DirectorId = 2,
                            Duration = 111,
                            Imdb = 8.1m,
                            ReleaseYear = new DateTime(2003, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kill Bill: Vol. 1"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The life journey of a simple man with a big heart.",
                            DirectorId = 3,
                            Duration = 142,
                            Imdb = 8.8m,
                            ReleaseYear = new DateTime(1994, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A WWII mission to save a paratrooper behind enemy lines.",
                            DirectorId = 4,
                            Duration = 169,
                            Imdb = 8.6m,
                            ReleaseYear = new DateTime(1998, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Saving Private Ryan"
                        });
                });

            modelBuilder.Entity("MovieApp.DAL.Models.Movie", b =>
                {
                    b.HasOne("MovieApp.DAL.Models.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("MovieApp.DAL.Models.Director", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
