// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.DAL.Data;

#nullable disable

namespace MovieApp.DAL.Data.Migrations
{
    [DbContext(typeof(MovieAppDbContext))]
    partial class MovieAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieApp.DAL.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Director", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "123 Hollywood Blvd, Los Angeles, CA",
                            Age = 77,
                            City = "Los Angeles",
                            Description = "An American filmmaker known for his work in the adventure and science fiction genres.",
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 2,
                            Adress = "456 Sunset St, Burbank, CA",
                            Age = 50,
                            City = "Burbank",
                            Description = "A British-American filmmaker known for his complex narratives and innovative storytelling techniques.",
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 3,
                            Adress = "789 Vine St, Los Angeles, CA",
                            Age = 58,
                            City = "Los Angeles",
                            Description = "An American filmmaker known for his stylized violence, sharp dialogue, and non-linear storytelling.",
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 4,
                            Adress = "321 Hollywood Blvd, New York, NY",
                            Age = 78,
                            City = "New York",
                            Description = "An American filmmaker known for his work in the crime and drama genres, often exploring themes of guilt and redemption.",
                            Name = "Martin Scorsese"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
